# -*- coding: utf-8 -*-
"""Untitled107.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_euRKrw2FNn_M7SKp20Fmi5QGkBKmD4b
"""

!pip install -q datasets pandas scikit-learn transformers accelerate torch

from datasets import load_dataset

dataset = load_dataset(
    "Hello-SimpleAI/HC3",
    "default",
    revision="refs/convert/parquet"
)

print(dataset)

print("Available splits:", dataset.keys())
print("Columns:", dataset["train"].column_names)

sample = dataset["train"][0]

print("\nQuestion:")
print(sample["question"])

print("\nHuman answers:")
print(sample["human_answers"])

print("\nChatGPT answers:")
print(sample["chatgpt_answers"])

import pandas as pd

rows = []

for example in dataset["train"]:
    question_id = example["id"]

    for answer in example["human_answers"]:
        if isinstance(answer, str) and answer.strip():
            rows.append({
                "question_id": question_id,
                "text": answer.strip(),
                "label": 0
            })

    for answer in example["chatgpt_answers"]:
        if isinstance(answer, str) and answer.strip():
            rows.append({
                "question_id": question_id,
                "text": answer.strip(),
                "label": 1
            })

df = pd.DataFrame(rows)

print("Dataset shape:", df.shape)
print(df.head())

from google.colab import files
files.download("hc3_cleaned.csv")

df = df.dropna(subset=["text"])
df["text"] = df["text"].astype(str).str.strip()

df = df[df["text"] != ""]
df = df.drop_duplicates(subset=["text"])
df = df.reset_index(drop=True)

print("Samples after cleaning:", len(df))
print("\nLabel distribution:")
print(df["label"].value_counts())

print("\nExample human text:")
print(df[df["label"] == 0]["text"].iloc[0][:500])

print("\nExample AI text:")
print(df[df["label"] == 1]["text"].iloc[0][:500])

df.to_csv("hc3_cleaned.csv", index=False)

print("Saved hc3_cleaned.csv")

import matplotlib.pyplot as plt

print("Dataset shape:", df.shape)

print("\nClass distribution:")
print(df["label"].value_counts().rename({
    0: "Human-written",
    1: "AI-generated"
}))

df["word_count"] = df["text"].str.split().str.len()

print("\nText length statistics:")
print(df["word_count"].describe())

df["label"].value_counts().sort_index().plot(
    kind="bar",
    rot=0
)

plt.xticks([0, 1], ["Human", "AI"])
plt.ylabel("Number of samples")
plt.title("Human vs AI Text Distribution")
plt.show()

from sklearn.model_selection import GroupShuffleSplit

split1 = GroupShuffleSplit(
    n_splits=1,
    test_size=0.30,
    random_state=42
)

train_idx, remaining_idx = next(
    split1.split(df, groups=df["question_id"])
)

train_df = df.iloc[train_idx].copy()
remaining_df = df.iloc[remaining_idx].copy()

split2 = GroupShuffleSplit(
    n_splits=1,
    test_size=0.50,
    random_state=42
)

val_idx, test_idx = next(
    split2.split(
        remaining_df,
        groups=remaining_df["question_id"]
    )
)

val_df = remaining_df.iloc[val_idx].copy()
test_df = remaining_df.iloc[test_idx].copy()

print("Training samples:", len(train_df))
print("Validation samples:", len(val_df))
print("Test samples:", len(test_df))

print("\nTraining labels:")
print(train_df["label"].value_counts())

print("\nValidation labels:")
print(val_df["label"].value_counts())

print("\nTest labels:")
print(test_df["label"].value_counts())

import numpy as np
from sklearn.metrics import accuracy_score, precision_recall_fscore_support, roc_auc_score

def compute_metrics(eval_pred):
    logits, labels = eval_pred

    predictions = np.argmax(logits, axis=-1)

    precision, recall, f1, _ = precision_recall_fscore_support(
        labels,
        predictions,
        average="binary",
        zero_division=0
    )

    accuracy = accuracy_score(labels, predictions)

    probabilities = np.exp(logits - np.max(logits, axis=1, keepdims=True))
    probabilities = probabilities / probabilities.sum(axis=1, keepdims=True)

    try:
        auc = roc_auc_score(labels, probabilities[:, 1])
    except ValueError:
        auc = 0.0

    return {
        "accuracy": accuracy,
        "precision": precision,
        "recall": recall,
        "f1": f1,
        "roc_auc": auc
    }

from transformers import TrainingArguments

training_args = TrainingArguments(
    output_dir="./ai_text_detector",
    num_train_epochs=3,
    learning_rate=2e-5,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",
    greater_is_better=False,
    weight_decay=0.01,
    save_total_limit=2,
    report_to="none",
    fp16=False
)

import pandas as pd
from sklearn.model_selection import GroupShuffleSplit
from transformers import AutoTokenizer, AutoModelForSequenceClassification, Trainer, DataCollatorWithPadding
from datasets import Dataset

# 1. Load the cleaned data from disk
df = pd.read_csv("hc3_cleaned.csv")

# 2. Perform the train/validation split
split1 = GroupShuffleSplit(n_splits=1, test_size=0.30, random_state=42)
train_idx, remaining_idx = next(split1.split(df, groups=df["question_id"]))

train_df = df.iloc[train_idx].copy()
remaining_df = df.iloc[remaining_idx].copy()

split2 = GroupShuffleSplit(n_splits=1, test_size=0.50, random_state=42)
val_idx, _ = next(split2.split(remaining_df, groups=remaining_df["question_id"]))
val_df = remaining_df.iloc[val_idx].copy()

# 3. Initialize the model and tokenizer
model = AutoModelForSequenceClassification.from_pretrained(
    "FacebookAI/xlm-roberta-base",
    num_labels=2
)
tokenizer = AutoTokenizer.from_pretrained("FacebookAI/xlm-roberta-base")

# 4. Convert to Hugging Face Datasets
train_dataset = Dataset.from_pandas(train_df[["text", "label"]])
val_dataset = Dataset.from_pandas(val_df[["text", "label"]])

# 5. Tokenization
def tokenize_function(examples):
    return tokenizer(examples["text"], truncation=True, max_length=128)

train_dataset = train_dataset.map(tokenize_function, batched=True)
val_dataset = val_dataset.map(tokenize_function, batched=True)

data_collator = DataCollatorWithPadding(tokenizer=tokenizer)

# 6. Initialize Trainer and Train
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=val_dataset,
    processing_class=tokenizer,
    data_collator=data_collator,
    compute_metrics=compute_metrics
)

trainer.train()

from datasets import Dataset


split2 = GroupShuffleSplit(n_splits=1, test_size=0.50, random_state=42)
_, test_idx = next(split2.split(remaining_df, groups=remaining_df["question_id"]))
test_df = remaining_df.iloc[test_idx].copy()

# 2. Convert to Hugging Face Dataset
test_dataset = Dataset.from_pandas(test_df[["text", "label"]])

# 3. Tokenize test dataset using the existing tokenizer
test_dataset = test_dataset.map(tokenize_function, batched=True)

# 4. Evaluate using the trainer
test_results = trainer.evaluate(test_dataset)

print("Test Results:")
for metric, value in test_results.items():
    print(f"{metric}: {value:.4f}")

model_save_path = "./fine_tuned_ai_text_detector"

trainer.save_model(model_save_path)
tokenizer.save_pretrained(model_save_path)

print("Model saved successfully!")

import torch
from transformers import AutoTokenizer, AutoModelForSequenceClassification

model_path = "./fine_tuned_ai_text_detector"

tokenizer = AutoTokenizer.from_pretrained(model_path)
model = AutoModelForSequenceClassification.from_pretrained(model_path)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)
model.eval()

def detect_ai_text(text):
    inputs = tokenizer(
        text,
        return_tensors="pt",
        truncation=True,
        max_length=256
    )

    inputs = {key: value.to(device) for key, value in inputs.items()}

    with torch.no_grad():
        outputs = model(**inputs)
        probabilities = torch.softmax(outputs.logits, dim=-1)[0]

    prediction = torch.argmax(probabilities).item()

    label = "AI-generated" if prediction == 1 else "Human-written"
    confidence = probabilities[prediction].item() * 100

    return {
        "prediction": label,
        "confidence": round(confidence, 2),
        "human_probability": round(probabilities[0].item() * 100, 2),
        "ai_probability": round(probabilities[1].item() * 100, 2)
    }

text = """
Artificial intelligence is transforming education by helping students
understand complex concepts, practice problem-solving, and receive
personalized feedback.
"""

print(detect_ai_text(text))

print("Training samples:", len(train_dataset))
print("Validation samples:", len(val_dataset))
print("Test samples:", len(test_dataset))

print("Training metrics:")
print(trainer.state.log_history[-5:])

print("Training labels:")
print(train_df["label"].value_counts())

print("\nValidation labels:")
print(val_df["label"].value_counts())

print("\nTest labels:")
print(test_df["label"].value_counts())

from sklearn.metrics import classification_report, confusion_matrix
import numpy as np

pred_output = trainer.predict(test_dataset)

y_true = pred_output.label_ids
y_pred = np.argmax(pred_output.predictions, axis=-1)

print(classification_report(
    y_true,
    y_pred,
    labels=[0, 1],
    target_names=["Human-written", "AI-generated"],
    digits=4,
    zero_division=0
))

print("Confusion matrix:")
print(confusion_matrix(y_true, y_pred))

import torch

THRESHOLD = 0.5

def detect_ai_text(text):
    inputs = tokenizer(
        text,
        return_tensors="pt",
        truncation=True,
        max_length=256
    )

    inputs = {
        key: value.to(device)
        for key, value in inputs.items()
    }

    with torch.no_grad():
        outputs = model(**inputs)
        probabilities = torch.softmax(outputs.logits, dim=-1)[0]

    ai_probability = probabilities[1].item()

    if ai_probability >= THRESHOLD:
        result = "AI-generated"
    else:
        result = "Not AI-generated"

    return result


text = """
Artificial intelligence is transforming education by helping
students understand complex concepts and solve problems.
"""

print(detect_ai_text(text))

test_paragraphs = [
    # 1. Informal personal writing
    """
    Yesterday I went to college a little late because my bus
    was delayed. I missed the first few minutes of class, but
    luckily my friend shared the notes with me. After college,
    we went to a nearby restaurant and had lunch together.
    """,

    # 2. Formal academic writing
    """
    Artificial intelligence has become an important area of
    research in recent years. Machine learning algorithms can
    identify patterns in large datasets and use these patterns
    to make predictions. These techniques are applied in
    healthcare, education, finance, and transportation.
    """,

    # 3. Personal opinion
    """
    In my opinion, online education is convenient, but it
    cannot completely replace classroom learning. Students
    can attend lectures from home, although some find it
    difficult to remain focused without direct interaction
    with teachers and classmates.
    """,

    # 4. Technical explanation
    """
    A database management system stores and organizes data
    so that applications can retrieve and update information
    efficiently. SQL is commonly used to query relational
    databases, create tables, and manage records.
    """,

    # 5. Casual conversational writing
    """
    I tried learning Python last month, but initially I found
    loops and functions confusing. After solving a few basic
    problems every day, things started making more sense.
    Practicing small programs helped me understand the concepts.
    """,

    # 6. Environmental topic
    """
    Plastic waste has become a serious environmental concern.
    Many plastic products are used for only a few minutes but
    remain in the environment for years. Reusing materials,
    recycling waste, and reducing unnecessary packaging can
    help limit plastic pollution.
    """,

    # 7. Student experience
    """
    Preparing for examinations is stressful when several
    subjects have assignments and deadlines at the same time.
    I usually make a list of topics and study the difficult
    ones first. Taking short breaks also helps me concentrate.
    """,

    # 8. Formal AI-style explanation
    """
    Cloud computing enables organizations to access computing
    resources over the internet without maintaining all the
    required infrastructure themselves. It provides flexible
    storage, scalable processing capacity, and services that
    can be adjusted according to changing workloads.
    """,

    # 9. Science explanation
    """
    Photosynthesis is the process through which green plants
    convert light energy into chemical energy. Plants use
    carbon dioxide and water to produce glucose and release
    oxygen. This process supports plant growth and contributes
    to the balance of gases in the atmosphere.
    """,

    # 10. Short passage
    """
    I enjoy playing cricket on weekends because it gives me
    an opportunity to exercise and spend time with friends.
    """,

    # 11. Software engineering
    """
    Software testing helps developers identify defects before
    an application is released. Unit tests examine individual
    components, while integration tests verify whether multiple
    components work together correctly. Automated testing can
    reduce repetitive manual work.
    """,

    # 12. Reflective writing
    """
    Sometimes progress feels slow even when we are putting
    in consistent effort. I have noticed that looking back
    at what I learned over the past few weeks helps me stay
    motivated. Small improvements eventually make a difference.
    """
]

for i, paragraph in enumerate(test_paragraphs, start=1):
    result = detect_ai_text(paragraph)
    print(f"Paragraph {i}: {result}")

import torch

def detect_ai_text_detailed(text):
    inputs = tokenizer(
        text,
        return_tensors="pt",
        truncation=True,
        max_length=256
    )

    inputs = {key: value.to(device) for key, value in inputs.items()}

    with torch.no_grad():
        outputs = model(**inputs)
        probabilities = torch.softmax(outputs.logits, dim=-1)[0]

    prediction = torch.argmax(probabilities).item()

    label = "AI-generated" if prediction == 1 else "Human-written"
    confidence = probabilities[prediction].item() * 100

    return {
        "prediction": label,
        "confidence": round(confidence, 2),
        "human_probability": round(probabilities[0].item() * 100, 2),
        "ai_probability": round(probabilities[1].item() * 100, 2)
    }

for i, paragraph in enumerate(test_paragraphs, start=1):
    result = detect_ai_text_detailed(paragraph)

    print(f"\nParagraph {i}")
    print("Prediction:", result["prediction"])
    print("Confidence:", result["confidence"], "%")
    print("Human probability:", result["human_probability"], "%")
    print("AI probability:", result["ai_probability"], "%")

with open("/content/nasa_news_articles_for_testing.txt", "r", encoding="utf-8") as f:
    news_text = f.read()

result = detect_ai_text(news_text)
print(result)

text_input = '''Earth is the third planet from the Sun and the only known planet that supports life. It is often called the Blue Planet because approximately 71% of its surface is covered with water. Earth provides the essential resources needed for the survival of humans, animals, and plants, including air, water, food, and suitable environmental conditions. Its atmosphere protects living organisms from harmful solar radiation and helps maintain a temperature that supports life.
The Earth consists of several layers, including the crust, mantle, outer core, and inner core. The crust is the outermost layer on which we live. It contains continents, mountains, valleys, forests, and oceans. The mantle lies beneath the crust and consists of hot rock that moves slowly over long periods. The outer core is mainly composed of liquid iron and nickel, while the inner core is extremely hot and remains solid because of immense pressure. These internal layers play an important role in Earth's geological activity, including earthquakes, volcanic eruptions, and the movement of tectonic plates.
Water is one of the most important resources on Earth. Oceans, rivers, lakes, glaciers, and underground water sources support ecosystems and human activities. Water is essential for drinking, agriculture, industry, and the survival of living organisms. Although Earth contains a large amount of water, most of it is salt water found in oceans. Only a small percentage is freshwater available for human use, making water conservation an important responsibility.
Earth's atmosphere consists mainly of nitrogen and oxygen, along with smaller amounts of other gases. It enables humans and animals to breathe and helps regulate the planet's temperature. The natural greenhouse effect keeps Earth warm enough to support life. However, human activities such as burning fossil fuels, deforestation, and industrial pollution increase the concentration of greenhouse gases. This contributes to global warming and climate change, which can lead to rising temperatures, melting glaciers, changing rainfall patterns, and more frequent extreme weather events.
Biodiversity is another essential feature of Earth. The planet is home to millions of species of plants, animals, fungi, and microorganisms. Forests provide oxygen, absorb carbon dioxide, and offer habitats for wildlife. Oceans support marine organisms and help regulate the global climate. Every species plays a role in maintaining ecological balance. However, habitat destruction, pollution, overexploitation of natural resources, and climate change threaten biodiversity worldwide.
Human beings depend heavily on Earth's natural resources for survival and development. Agriculture provides food, forests supply timber, and minerals support industries and technological advancements. However, excessive consumption and unsustainable practices can damage the environment. Deforestation reduces wildlife habitats, plastic waste pollutes water bodies, and air pollution affects human health. These problems demonstrate the importance of responsible resource management.
Protecting Earth requires cooperation among individuals, communities, governments, and industries. People can contribute by planting trees, conserving water, reducing plastic usage, recycling waste, and using energy efficiently. Renewable energy sources such as solar and wind power can reduce dependence on fossil fuels. Governments and organizations can support environmental protection through sustainable policies, conservation programs, and public awareness campaigns. Education also plays a significant role in encouraging people to adopt environmentally friendly habits.
In conclusion, Earth is a remarkable planet that provides everything necessary for life. Its natural systems, diverse ecosystems, and abundant resources make it our most valuable home. However, environmental challenges threaten the balance that supports living organisms. Every individual has a responsibility to protect the planet and use its resources wisely. By adopting sustainable practices and working together, humanity can help preserve Earth's beauty and natural wealth for future generations. Protecting Earth is not merely a choice but a shared responsibility that determines the future of life on our planet.'''

result = detect_ai_text(text_input)
print(result)

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.metrics import (
    confusion_matrix,
    ConfusionMatrixDisplay,
    roc_curve,
    roc_auc_score,
    classification_report
)

# 1. Get predictions on the existing test dataset
pred_output = trainer.predict(test_dataset)

y_true = pred_output.label_ids
logits = pred_output.predictions

# Convert logits to probabilities using softmax
exp_logits = np.exp(logits - np.max(logits, axis=1, keepdims=True))
probabilities = exp_logits / exp_logits.sum(axis=1, keepdims=True)

# Class 1 = AI-generated
ai_probabilities = probabilities[:, 1]
y_pred = np.argmax(logits, axis=1)

# 2. Confusion Matrix
cm = confusion_matrix(y_true, y_pred, labels=[0, 1])

plt.figure(figsize=(6, 5))
sns.heatmap(
    cm, annot=True, fmt="d", cmap="Blues",
    xticklabels=["Human", "AI-generated"],
    yticklabels=["Human", "AI-generated"]
)
plt.xlabel("Predicted Label")
plt.ylabel("Actual Label")
plt.title("Confusion Matrix - XLM-RoBERTa")
plt.tight_layout()
plt.show()

# 3. ROC Curve
fpr, tpr, thresholds = roc_curve(y_true, ai_probabilities)
auc_score = roc_auc_score(y_true, ai_probabilities)

plt.figure(figsize=(6, 5))
plt.plot(fpr, tpr, label=f"ROC-AUC = {auc_score:.4f}")
plt.plot([0, 1], [0, 1], "--", label="Random classifier")
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curve")
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

# 4. Precision, Recall, F1-score
report = classification_report(
    y_true,
    y_pred,
    labels=[0, 1],
    target_names=["Human-written", "AI-generated"],
    output_dict=True
)

metrics = ["precision", "recall", "f1-score"]
classes = ["Human-written", "AI-generated"]

x = np.arange(len(classes))
width = 0.24

plt.figure(figsize=(8, 5))
for i, metric in enumerate(metrics):
    values = [report[c][metric] for c in classes]
    plt.bar(x + (i - 1) * width, values, width, label=metric)

plt.xticks(x, classes)
plt.ylabel("Score")
plt.ylim(0, 1.05)
plt.title("Classification Performance by Class")
plt.legend()
plt.tight_layout()
plt.show()

# 5. Training Loss vs Validation Loss
history = trainer.state.log_history

train_logs = [
    item for item in history
    if "loss" in item and "eval_loss" not in item
]
eval_logs = [
    item for item in history
    if "eval_loss" in item
]

plt.figure(figsize=(8, 5))

if train_logs:
    plt.plot(
        [item["step"] for item in train_logs],
        [item["loss"] for item in train_logs],
        marker="o",
        label="Training Loss"
    )

if eval_logs:
    plt.plot(
        [item["step"] for item in eval_logs],
        [item["eval_loss"] for item in eval_logs],
        marker="s",
        label="Validation Loss"
    )

plt.xlabel("Training Step")
plt.ylabel("Loss")
plt.title("Training vs Validation Loss")
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

print("Test ROC-AUC:", round(auc_score, 4))
print(classification_report(
    y_true, y_pred,
    target_names=["Human-written", "AI-generated"]
))